
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3307/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
    show-sql: true